<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Loading_normal_login_password</name>
   <tag></tag>
   <elementGuidId>25848d67-b350-425b-be40-6404136d20e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#normal_login_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='normal_login_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ec83976-a2ab-4573-880f-101592f2f1fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>53f9d6b2-10ef-4c4b-b580-a2ab33c2a83e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>edbb4a01-40d1-4b15-a313-45d7179cafa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>normal_login_password</value>
      <webElementGuid>29b87c2a-53f9-4bc1-883e-eab5aa06fdea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>987d1929-17a6-4813-a75e-b62f685d7a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-lg css-obcdh2</value>
      <webElementGuid>714cd876-f816-426d-84ca-c3b43cf1e0f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>testing123</value>
      <webElementGuid>1a66e5fb-4cb8-4009-a768-94adb0daef47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;normal_login_password&quot;)</value>
      <webElementGuid>8c42062d-1f1f-4554-b167-2bd106013f83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='normal_login_password']</value>
      <webElementGuid>7061873b-0629-4982-bec7-ff76591664b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='normal_login']/div[7]/div[2]/div/div/div/div/div/div/span/input</value>
      <webElementGuid>9d2a89a3-8969-49e1-bed8-098f5fd0c12a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/span/input</value>
      <webElementGuid>16cd805a-9ed9-4178-84db-0602591cc2ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Password' and @id = 'normal_login_password']</value>
      <webElementGuid>88479c36-04ac-47a5-ac16-8d1d1458a0ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
