<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Loading_normal_login_password</name>
   <tag></tag>
   <elementGuidId>ed4cfc81-8777-4328-9dfc-e772a681621f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#normal_login_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='normal_login_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>12e87de7-a151-49da-b152-99dc7aa2aa3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>62252015-033e-4e80-b324-6d45e2622182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>cc71eea5-6aac-4938-ad70-67002fd7a60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>normal_login_password</value>
      <webElementGuid>57291cad-2f86-4c8c-b6aa-08b06f103dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6d636f88-796c-4160-86f2-968b84ebb088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-lg css-obcdh2</value>
      <webElementGuid>c61ea038-4041-4743-8930-32a79add6b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>testing123</value>
      <webElementGuid>770501d5-815f-453e-b63f-898d1f96304e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;normal_login_password&quot;)</value>
      <webElementGuid>0890200e-1262-4f6c-a9d8-fe466c269e96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='normal_login_password']</value>
      <webElementGuid>df750c69-fc27-4888-afd4-8cf3b99f7ec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='normal_login']/div[7]/div[2]/div/div/div/div/div/div/span/input</value>
      <webElementGuid>8548047d-6ac8-4cca-9540-fc3b9278b9f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/span/input</value>
      <webElementGuid>517b7d1d-6755-496f-98f3-3baac75621cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Password' and @id = 'normal_login_password']</value>
      <webElementGuid>9dc3d6ab-aa71-4fb9-9f0c-6babe87dc128</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
