<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_1995</name>
   <tag></tag>
   <elementGuidId>a9314023-0afb-4aa7-910b-8bd32003ca47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[110]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7644f53b-36d7-4d23-b78e-81640fddda7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>81cf67f5-dcf1-4476-9a6e-e7557c69290c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>afe4e582-a718-4e77-999e-39d90ce8a5ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>db56c256-642b-4a31-a3f1-87f3f6768b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>36dea3fa-a6c3-4eff-8a24-df2ea55ef528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiYearCalendar-button css-fqcqoi</value>
      <webElementGuid>b291c644-0048-4300-90f3-910e7f143ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1995</value>
      <webElementGuid>3518e95e-b99d-481a-bae4-997840a80045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiPopper-root MuiPickerPopper-root css-q6vpb4&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation8 MuiPickerPopper-paper css-1r3tlof&quot;]/div[@class=&quot;MuiPickersLayout-root css-16juibx&quot;]/div[@class=&quot;MuiPickersLayout-contentWrapper css-1nc6gt7&quot;]/div[@class=&quot;MuiDateCalendar-root css-w6tl5u&quot;]/div[@class=&quot;MuiPickersFadeTransitionGroup-root MuiDateCalendar-viewTransitionContainer css-1yac7xg&quot;]/div[1]/div[@class=&quot;MuiYearCalendar-root css-1cky2ox&quot;]/button[@class=&quot;MuiYearCalendar-button css-fqcqoi&quot;]</value>
      <webElementGuid>04c99ede-5c4f-490b-8f02-6811111de35a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[110]</value>
      <webElementGuid>fb244282-c750-4bac-856a-60c336343902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='June 2025'])[1]/following::button[99]</value>
      <webElementGuid>3587dea4-7144-4757-a59c-577d99736a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::button[99]</value>
      <webElementGuid>132be780-4a1f-4297-9d33-1b1280cc5629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1995']/parent::*</value>
      <webElementGuid>0cf70a60-32b8-4ac7-9ef7-0cfb04f1d61d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[96]</value>
      <webElementGuid>df6a1e4a-9d69-40b4-98d3-9559ea547ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '1995' or . = '1995')]</value>
      <webElementGuid>6552fb6c-612c-4d94-ad1f-b70417035557</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
