<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Profile Information_nrp</name>
   <tag></tag>
   <elementGuidId>c7820cf2-2344-4196-810e-1f4ce57ae333</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nrp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nrp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2fd37aef-285d-409a-b288-be84441aac91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fc82e774-ce11-4504-bddb-8774d54cef51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nrp</value>
      <webElementGuid>c6019e7f-37d0-452c-b9c2-2c45c5db88b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Value..</value>
      <webElementGuid>190b0e6a-e22f-42c2-872c-26428ac93aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall MuiInputBase-inputHiddenLabel css-15v65ck</value>
      <webElementGuid>e1abbb5d-a2f3-4584-b7d1-4603584cc5f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>39921e66-8c68-4a98-b689-d4f4fbf99c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nrp</value>
      <webElementGuid>5040ebd2-b753-41af-af5d-cccbd790fdf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nrp&quot;)</value>
      <webElementGuid>dd43f8f7-454a-4772-8893-119885ea9a84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nrp']</value>
      <webElementGuid>aab66009-fc59-490b-9afd-097b474bc70d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>9e13f6b6-044a-40f4-bc60-9239b951aad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nrp' and @placeholder = 'Enter Value..' and @type = 'text' and @name = 'nrp']</value>
      <webElementGuid>0101b4da-0a8c-442b-864b-a17579154e75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
