<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Age_pendidikan</name>
   <tag></tag>
   <elementGuidId>9ab43fbd-7a47-4ddf-836f-934634859d07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiInputBase-root.MuiOutlinedInput-root.MuiInputBase-colorPrimary.MuiInputBase-fullWidth.Mui-focused.MuiInputBase-formControl.MuiInputBase-sizeSmall.MuiInputBase-hiddenLabel.css-12khbr3 > #pendidikan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='pendidikan'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>84e9e5f8-2025-4771-a722-e7b2d2b8da0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>15714b5a-d23f-4ab0-9ad0-c155c6988043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pendidikan</value>
      <webElementGuid>c29dcee4-9b3d-4650-9904-64612425e36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Value..</value>
      <webElementGuid>bd88d314-d9d1-44cd-985f-bf46b410df10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall MuiInputBase-inputHiddenLabel css-15v65ck</value>
      <webElementGuid>b2da1563-bd43-40af-b63b-da779b3c65e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6bf52939-5e68-407d-9371-415637fec52b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pendidikan</value>
      <webElementGuid>53dcbe96-59f4-43a1-8c29-9d4c6e5ed86a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;mainwrapper css-hboir5&quot;]/div[@class=&quot;page-wrapper css-3hl8as&quot;]/div[@class=&quot;MuiBox-root css-bampo8&quot;]/div[@class=&quot;MuiBox-root css-1bu8bos&quot;]/div[1]/div[@class=&quot;MuiContainer-root css-1v6p5b&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiCard-root css-1a67fd8&quot;]/div[@class=&quot;MuiCardContent-root css-15q2cw4&quot;]/div[@class=&quot;MuiBox-root css-xy3juv&quot;]/div[@class=&quot;MuiStack-root css-3lm9t3&quot;]/div[@class=&quot;MuiFormControl-root MuiFormControl-fullWidth MuiTextField-root css-1vbfw84&quot;]/div[@class=&quot;MuiInputBase-root MuiOutlinedInput-root MuiInputBase-colorPrimary MuiInputBase-fullWidth Mui-focused MuiInputBase-formControl MuiInputBase-sizeSmall MuiInputBase-hiddenLabel css-12khbr3&quot;]/input[@id=&quot;pendidikan&quot;]</value>
      <webElementGuid>32919f2f-fedb-4394-9d73-f2bd29b0fb62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='pendidikan'])[2]</value>
      <webElementGuid>2a2498a2-e9ee-44e2-9671-3ba47800099e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/input</value>
      <webElementGuid>7057d28f-8491-4369-964c-170dcb928526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pendidikan' and @placeholder = 'Enter Value..' and @type = 'text' and @name = 'pendidikan']</value>
      <webElementGuid>85fac101-0e1d-4bcc-86e6-89ad4d6d97b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
