<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Profile Information_pendidikan</name>
   <tag></tag>
   <elementGuidId>01b7f42b-81a0-41ad-8fb4-a5d04b50d6f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pendidikan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pendidikan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3dbbff4c-6bb0-4f30-af36-b69680d3782a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>47e007cb-ccb7-45a8-b6f2-5f7feba0ffd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pendidikan</value>
      <webElementGuid>d68f4c40-bf14-49a3-9a6f-5155122f3742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Value..</value>
      <webElementGuid>83b9ea44-2244-4cdb-8ea5-50387139069e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall MuiInputBase-inputHiddenLabel css-15v65ck</value>
      <webElementGuid>9bc81ad6-0381-44f3-8868-21031c1519b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>55158420-af37-4ba6-b8dd-b0963870c557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pendidikan</value>
      <webElementGuid>3dc471dd-1312-49c9-8d6f-6dc8a4380871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;mainwrapper css-hboir5&quot;]/div[@class=&quot;page-wrapper css-3hl8as&quot;]/div[@class=&quot;MuiBox-root css-bampo8&quot;]/div[@class=&quot;MuiBox-root css-1bu8bos&quot;]/div[1]/div[@class=&quot;MuiContainer-root css-1v6p5b&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiCard-root css-1a67fd8&quot;]/div[@class=&quot;MuiCardContent-root css-15q2cw4&quot;]/div[@class=&quot;MuiBox-root css-xy3juv&quot;]/div[@class=&quot;MuiStack-root css-3lm9t3&quot;]/div[@class=&quot;MuiFormControl-root MuiFormControl-fullWidth MuiTextField-root css-1vbfw84&quot;]/div[@class=&quot;MuiInputBase-root MuiOutlinedInput-root MuiInputBase-colorPrimary MuiInputBase-fullWidth MuiInputBase-formControl MuiInputBase-sizeSmall MuiInputBase-hiddenLabel css-12khbr3&quot;]/input[@id=&quot;pendidikan&quot;]</value>
      <webElementGuid>bc2203a5-b936-47b3-ac94-8afc3f14ce61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pendidikan']</value>
      <webElementGuid>85be6911-e67b-44cf-bbd1-96e9608c3bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>4ce33607-2089-4597-b56d-b3f28852ca08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pendidikan' and @placeholder = 'Enter Value..' and @type = 'text' and @name = 'pendidikan']</value>
      <webElementGuid>5f78c655-1bd1-4fe0-ad4b-e1ddc3d0af3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
